project:
  type: website

website:
  title: "FSCI2024 C03"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto