project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
  
website:
  title: "FSCI2024 C03"
  page-footer:
    center: "Created with [Quarto](https://quarto.org/) (+ love) by [Bella](https://bellaratmelia.github.io) and [Danping](https://dpdong19.github.io/)"   
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - sidebar:materials
  sidebar:
    - id: materials
      title: "Materials"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - session-01.qmd
        - session-02.qmd
        - session-03.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    
  revealjs: 
    theme: [default, custom.scss]
    width: 1920
    height: 1080
    slide-number: true
    footer: "[C03 Making Research More Transparent with Quarto and RStudio](https://bellaratmelia.github.io/2024-fsci-quarto/)"
    chalkboard: false
    logo: "images/smu logo.png"
    incremental: true

editor: visual

execute:
  freeze: auto