project:
  type: website
  output-dir: _site
  
website:
  title: "FSCI2024 C03"
  body-footer: "Created with [Quarto](https://quarto.org/) (+ love) by [Bella](https://bellaratmelia.github.io) and [Danping](https://dpdong19.github.io/)"   
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto